#E-Commerce Customer Churn & Revenue Analysis

In [1]:
import pandas as pd
df = pd.read_csv(r"C:/Users/hp/Documents/Project/Data/Customer_Churn_Data.csv")
df

,Customer ID,Purchase Date,Product Category,Product Price,Quantity,Total Purchase Amount,Payment Method,Customer Age,Returns,Customer Name,Age,Gender,Churn
0,46251,08-09-2020 09:38,Electronics,12,3,740,Credit Card,37,0.0,Christine Hernandez,37,Male,0
1,46251,05-03-2022 12:56,Home,468,4,2739,PayPal,37,0.0,Christine Hernandez,37,Male,0
2,46251,23-05-2022 18:18,Home,288,2,3196,PayPal,37,0.0,Christine Hernandez,37,Male,0
3,46251,12-11-2020 13:13,Clothing,196,1,3509,PayPal,37,0.0,Christine Hernandez,37,Male,0
4,13593,27-11-2020 17:55,Home,449,1,3452,Credit Card,49,0.0,James Grant,49,Female,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
249995,33308,10-08-2023 13:39,Clothing,279,2,2187,PayPal,55,1.0,Michelle Flores,55,Male,1
249996,48835,23-11-2021 01:30,Home,27,1,3615,Credit Card,42,1.0,Jeremy Rush,42,Female,1
249997,21019,02-07-2020 14:04,Home,17,5,2466,Cash,41,0.0,Tina Craig,41,Male,0
249998,49234,30-12-2020 02:02,Books,398,2,3668,Crypto,34,0.0,Jennifer Cooper,34,Female,1
249999,16971,13-03-2021 16:28,Electronics,425,4,2370,Cash,36,1.0,Justin Lawson,36,Female,1

In [2]:
df.head()

,Customer ID,Purchase Date,Product Category,Product Price,Quantity,Total Purchase Amount,Payment Method,Customer Age,Returns,Customer Name,Age,Gender,Churn
0,46251,08-09-2020 09:38,Electronics,12,3,740,Credit Card,37,0.0,Christine Hernandez,37,Male,0
1,46251,05-03-2022 12:56,Home,468,4,2739,PayPal,37,0.0,Christine Hernandez,37,Male,0
2,46251,23-05-2022 18:18,Home,288,2,3196,PayPal,37,0.0,Christine Hernandez,37,Male,0
3,46251,12-11-2020 13:13,Clothing,196,1,3509,PayPal,37,0.0,Christine Hernandez,37,Male,0
4,13593,27-11-2020 17:55,Home,449,1,3452,Credit Card,49,0.0,James Grant,49,Female,1

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 13 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Customer ID            250000 non-null  int64
 1   Purchase Date          250000 non-null  object
 2   Product Category       250000 non-null  object
 3   Product Price          250000 non-null  int64
 4   Quantity               250000 non-null  int64
 5   Total Purchase Amount  250000 non-null  int64
 6   Payment Method         250000 non-null  object
 7   Customer Age           250000 non-null  int64
 8   Returns                202404 non-null  float64
 9   Customer Name          250000 non-null  object
 10  Age                    250000 non-null  int64
 11  Gender                 250000 non-null  object
 12  Churn                  250000 non-null  int64
dtypes: float64(1), int64(7), object(5)
memory usage: 24.8+ MB

In [4]:
df.describe()

,Customer ID,Product Price,Quantity,Total Purchase Amount,Customer Age,Returns,Age,Churn
count,250000.00000,250000.000000,250000.000000,250000.000000,250000.000000,202404.000000,250000.000000,250000.000000
mean,25004.03624,254.659512,2.998896,2725.370732,43.940528,0.497861,43.940528,0.199496
std,14428.27959,141.568577,1.414694,1442.933565,15.350246,0.499997,15.350246,0.399622
min,1.00000,10.000000,1.000000,100.000000,18.000000,0.000000,18.000000,0.000000
25%,12497.75000,132.000000,2.000000,1477.000000,31.000000,0.000000,31.000000,0.000000
50%,25018.00000,255.000000,3.000000,2724.000000,44.000000,0.000000,44.000000,0.000000
75%,37506.00000,377.000000,4.000000,3974.000000,57.000000,1.000000,57.000000,0.000000
max,50000.00000,500.000000,5.000000,5350.000000,70.000000,1.000000,70.000000,1.000000

In [5]:
df.isnull().sum()

Customer ID                  0
Purchase Date                0
Product Category             0
Product Price                0
Quantity                     0
Total Purchase Amount        0
Payment Method               0
Customer Age                 0
Returns                  47596
Customer Name                0
Age                          0
Gender                       0
Churn                        0
dtype: int64

In [6]:
mode_val = df['Returns'].mode()[0]

In [7]:
df['Returns'] = df['Returns'].fillna(mode_val)
df['Returns'] = df['Returns'].astype(int)

In [8]:
df.isnull().sum()

Customer ID              0
Purchase Date            0
Product Category         0
Product Price            0
Quantity                 0
Total Purchase Amount    0
Payment Method           0
Customer Age             0
Returns                  0
Customer Name            0
Age                      0
Gender                   0
Churn                    0
dtype: int64

The `Purchase_Date` column is currently an object (string). We convert it to `datetime` format

In [9]:
df['Purchase Date'] = pd.to_datetime(df['Purchase Date'], dayfirst=True, format='mixed')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 13 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Customer ID            250000 non-null  int64
 1   Purchase Date          250000 non-null  datetime64[ns]
 2   Product Category       250000 non-null  object
 3   Product Price          250000 non-null  int64
 4   Quantity               250000 non-null  int64
 5   Total Purchase Amount  250000 non-null  int64
 6   Payment Method         250000 non-null  object
 7   Customer Age           250000 non-null  int64
 8   Returns                250000 non-null  int64
 9   Customer Name          250000 non-null  object
 10  Age                    250000 non-null  int64
 11  Gender                 250000 non-null  object
 12  Churn                  250000 non-null  int64
dtypes: datetime64[ns](1), int64(8), object(4)
memory usage: 24.8+ MB

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df.drop(columns=['Age'], inplace=True)

In [13]:
df.columns

Index(['Customer ID', 'Purchase Date', 'Product Category', 'Product Price',
       'Quantity', 'Total Purchase Amount', 'Payment Method', 'Customer Age',
       'Returns', 'Customer Name', 'Gender', 'Churn'],
      dtype='object')

**Transaction_Value:** Created by multiplying `Product_Price` and `Quantity` to represent the actual revenue generated per row

In [14]:
df['Transaction_Value'] = df['Product Price'] * df['Quantity']

In [15]:
df.rename(columns={'Total Purchase Amount': 'Lifetime_Spend'}, inplace=True)
df[['Product Price', 'Quantity', 'Transaction_Value', 'Lifetime_Spend']].head()

   Product Price  Quantity  Transaction_Value  Lifetime_Spend
0             12         3                 36             740
1            468         4               1872            2739
2            288         2                576            3196
3            196         1                196            3509
4            449         1                449            3452

**Month & Year Extraction:** We extract the month and year from `Purchase_Date`. This allows us to track seasonality, monthly sales growth, and yearly churn trends

In [16]:
df['Month'] = df['Purchase Date'].dt.month

In [17]:
df['Year'] = df['Purchase Date'].dt.year

**Age_Group:** Customers are segmented into demographic bins (Teen, Young Adult, Adult, Senior, Old) to analyze spending patterns by life stage

In [18]:
bins = [0, 18, 30, 45, 60, 100]
labels = ['Teen', 'Young Adult', 'Adult', 'Senior', 'Old']

df['Age Group'] = pd.cut(df['Customer Age'], bins=bins, labels=labels)

In [19]:
df.columns

Index(['Customer ID', 'Purchase Date', 'Product Category', 'Product Price',
       'Quantity', 'Lifetime_Spend', 'Payment Method', 'Customer Age',
       'Returns', 'Customer Name', 'Gender', 'Churn', 'Transaction_Value',
       'Month', 'Year', 'Age Group'],
      dtype='object')

In [20]:
df.columns = df.columns.str.replace(' ', '_')

In [21]:
df = df.sort_values(by=['Customer_ID','Purchase_Date'])
df[df['Customer_ID'] == 46251]

,Customer_ID,Purchase_Date,Product_Category,Product_Price,Quantity,Lifetime_Spend,Payment_Method,Customer_Age,Returns,Customer_Name,Gender,Churn,Transaction_Value,Month,Year,Age_Group
0,46251,2020-09-08 09:38:00,Electronics,12,3,740,Credit Card,37,0,Christine Hernandez,Male,0,36,9,2020,Adult
3,46251,2020-11-12 13:13:00,Clothing,196,1,3509,PayPal,37,0,Christine Hernandez,Male,0,196,11,2020,Adult
1,46251,2022-03-05 12:56:00,Home,468,4,2739,PayPal,37,0,Christine Hernandez,Male,0,1872,3,2022,Adult
2,46251,2022-05-23 18:18:00,Home,288,2,3196,PayPal,37,0,Christine Hernandez,Male,0,576,5,2022,Adult

**Key Finding:** Sorting revealed that `Lifetime_Spend` does not always increase chronologically. Because of this inconsistency, we will rely on our calculated `Transaction_Value` for revenue analysis

In [22]:
df = df.reset_index(drop=True)

In [23]:
df.Transaction_Value.sum()

np.int64(190908939)

In [24]:
df.groupby('Product_Category')['Transaction_Value'].sum().sort_values(ascending=False)

Product_Category
Clothing       57281185
Books          56999997
Electronics    38449938
Home           38177819
Name: Transaction_Value, dtype: int64

In [25]:
df.groupby('Year')['Transaction_Value'].sum()

Year
2020    51960327
2021    51272071
2022    51099870
2023    36576671
Name: Transaction_Value, dtype: int64

In [26]:
df.groupby('Year')['Customer_ID'].nunique()

Year
2020    37131
2021    36935
2022    36907
2023    30817
Name: Customer_ID, dtype: int64

In [27]:
df['Churn'].value_counts(normalize=True)*100

Churn
0    80.0504
1    19.9496
Name: proportion, dtype: float64

In [28]:
df.groupby('Year')['Churn'].sum()

Year
2020    13483
2021    13282
2022    13510
2023     9599
Name: Churn, dtype: int64

In [29]:
df.groupby('Year')['Churn'].mean() * 100

Year
2020    19.814828
2021    19.794632
2022    20.113445
2023    20.129176
Name: Churn, dtype: float64

In [30]:
df.groupby('Product_Category')['Churn'].mean().sort_values(ascending=False) * 100

Product_Category
Home           20.202203
Books          19.924712
Electronics    19.884428
Clothing       19.850237
Name: Churn, dtype: float64

In [31]:
df.groupby('Age_Group', observed=False)['Churn'].mean().sort_values(ascending=False) * 100

Age_Group
Teen           22.606436
Young Adult    20.231305
Senior         20.019917
Old            19.659819
Adult          19.655967
Name: Churn, dtype: float64

In [32]:
df['Payment_Method'].value_counts()

Payment_Method
Credit Card    100486
PayPal          74837
Cash            49894
Crypto          24783
Name: count, dtype: int64

In [33]:
df.groupby('Payment_Method')['Churn'].mean().sort_values(ascending=False) * 100

Payment_Method
Cash           20.004409
Credit Card    19.986864
PayPal         19.887222
Crypto         19.876528
Name: Churn, dtype: float64

In [34]:
df.groupby('Year')['Returns'].mean() * 100

Year
2020    40.473216
2021    40.315057
2022    39.979753
2023    40.522574
Name: Returns, dtype: float64

In [35]:
df.groupby('Product_Category')['Returns'].mean().sort_values(ascending=False) * 100

Product_Category
Home           40.414435
Electronics    40.392548
Books          40.352680
Clothing       40.134840
Name: Returns, dtype: float64

In [36]:
df.groupby('Returns')['Churn'].mean() * 100

Returns
0    19.904041
1    20.017069
Name: Churn, dtype: float64

In [41]:
!pip install pymysql sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pymysql in c:\users\hp\appdata\roaming\python\python313\site-packages (1.1.2)
Requirement already satisfied: sqlalchemy in c:\programdata\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)

In [45]:
from sqlalchemy import create_engine

user = 'root'
password = 'dhairya99'
host = 'localhost'
port = '3306'
db_name = 'customer_churn_analysis'

engine = create_engine(f'mysql+pymysql://{user}:{password}@{host}:{port}/{db_name}')

df.to_sql(name='customer_data', con=engine, if_exists='replace', index=False)
print("✅ Success! Data exported to MySQL.")

✅ Success! Data exported to MySQL.